### ISSUE TITLE
ksql-workshop

### ISSUE THREAD

**Issue by husenzhang** [confluentinc/demo-scene#108]
elasticsearch      /usr/local/bin/docker-entr ...   Exit 78

**Comment by rmoff** [comment]
You'll need to provide a bit more context than that :) 

What version are you running, on what machine, what do the logs say, etc.

**Comment by husenzhang** [comment]
:)  
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
-----------------------------------------
KiB Mem : 32577552 total,  6598028 free, 15710732 used, 10268792 buff/cache
----------------------------------------------
ubuntu@ip-172-31-175-251:~/demo-scene/ksql-workshop$ ls
README.adoc         images                      ksql-workshop.sql    scripts
data                ksql-workshop-windows.adoc  nginx                websockets
docker-compose.yml  ksql-workshop.adoc          pre-requisites.adoc
ubuntu@ip-172-31-175-251:~/demo-scene/ksql-workshop$ docker-compose ps
      Name                    Command                  State                              Ports
-----------------------------------------------------------------------------------------------------------------------
connect-debezium   /docker-entrypoint.sh start      Up             0.0.0.0:8083->8083/tcp, 8778/tcp, 9092/tcp, 9779/tcp
control-center     bash -c echo "Waiting two  ...   Up             0.0.0.0:9021->9021/tcp
datagen-ratings    bash -c echo Waiting for K ...   Up
elasticsearch      /usr/local/bin/docker-entr ...   Exit 78
kafka              /etc/confluent/docker/run        Up             0.0.0.0:9092->9092/tcp
kafka-connect      /etc/confluent/docker/run        Up (healthy)   0.0.0.0:18083->18083/tcp, 8083/tcp, 9092/tcp
kafkacat           sleep infinity                   Up
kibana             /usr/local/bin/kibana-docker     Up             0.0.0.0:5601->5601/tcp
ksql-cli           /bin/sh                          Up
ksql-server        /etc/confluent/docker/run        Up             0.0.0.0:8088->8088/tcp
mysql              docker-entrypoint.sh mysqld      Up             0.0.0.0:3306->3306/tcp, 33060/tcp
nginx              nginx -g daemon off;             Up             80/tcp, 0.0.0.0:8080->8080/tcp
schema-registry    /etc/confluent/docker/run        Up             8081/tcp
websockets         docker-entrypoint.sh bash  ...   Up             3000/tcp
zookeeper          /etc/confluent/docker/run        Up             2181/tcp, 2888/tcp, 3888/tcp

**Comment by husenzhang** [comment]
thanks robin.  logs showed vm.max_map_count was too low.  fixed the issue after:
sudo sysctl -w vm.max_map_count=262144
not sure if i need to do above command each time i log into the box

**Comment by rmoff** [comment]
Great, glad you sorted it. 
There's instructions [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html) for making this config change permanent.
