### ISSUE TITLE
Kafka Connect docker not working properly (unhealthy)

### ISSUE THREAD

**Issue by FazeelAkhtar** [confluentinc/demo-scene#111]
Hi,
i am trying to run following , all docker containers are healthy and working except 
**confluentinc/cp-kafka-connect:5.4.0-beta1** (unhealthy)

git clone https://github.com/confluentinc/demo-scene.git
cd demo-scene/rabbitmq-into-kafka

any ideas or what can i do to make it healthy or should choose another container for rabbitmq source to connect with Kafka Connect.

Thanks
Fazeel

**Comment by rmoff** [comment]
What branch are you working from? 
Do you see any errors in the Kafka Connect worker log?

**Comment by FazeelAkhtar** [comment]
I am trying to follow on of your guide 
https://rmoff.net/2020/01/08/streaming-messages-from-rabbitmq-into-kafka-with-kafka-connect/
eveytime i run docker compose - either connect docker is not running properly or
my main issue is i am unable to run **kafka conntect worker**  can you check that? 

it would be really helpfull if you can give me some pointer why  worker is not running proerly. 

Thanks
Fazeel

**Comment by FazeelAkhtar** [comment]
<img width="1440" alt="Screen Shot 2020-03-14 at 11 55 08 PM" src="https://user-images.githubusercontent.com/1505958/76691821-60c20900-664f-11ea-9b0e-fdcb205a1ddd.png">

**Comment by rmoff** [comment]
Do you see any errors in the Kafka Connect worker log?

**Comment by FazeelAkhtar** [comment]
How can i get to the connect logs, i am trying to see logs but no success, also i saw there is mongo running with syslogs. 

Is it possible this issue is related to some specific kafka versions,
 My main goal is to run an example which connect to DB via Kafka connect and stream data inside kafa. if you have any other sample to try can you point out?
Thanks for answering. :)

**Comment by rmoff** [comment]
`docker-compose logs -f kafka-connect` should give you the logs.

**Comment by sobychacko** [comment]
@rmoff I also see the same behavior. I am running `docker-compose up -d` from this directory: `demo-scene/kafka-connect-zero-to-hero` (master). Initially, it shows the status as below.
```
docker ps
CONTAINER ID        IMAGE                                    COMMAND                   CREATED             STATUS                            PORTS                               NAMES
aad55fc43ff9        edenhill/kafkacat:1.5.0                  "/bin/sh -c 'apk add…"    3 minutes ago       Up 3 minutes                                                          kafkacat
47a01f412761        confluentinc/cp-kafka-connect:5.4.1      "bash -c 'echo \"Inst…"   3 minutes ago       Up 3 minutes (health: starting)   0.0.0.0:8083->8083/tcp, 9092/tcp    kafka-connect
```
and then a little bit later changing the status to `unhealthy`. 

The log for connect seems to be stuck at loading some plugins:

```
[2020-04-28 21:51:23,768] INFO Registered loader: PluginClassLoader{pluginLocation=file:/usr/share/java/kafka-connect-jms/} (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:264)
[2020-04-28 21:51:23,770] INFO Added plugin 'io.confluent.connect.jms.JmsSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:193)
[2020-04-28 21:51:23,850] INFO Loading plugin from: /usr/share/java/kafka-connect-ibmmq (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader:241)
```
A few times I tried, it is stuck at similar points in the log, but with different plugins.

**Comment by rmoff** [comment]
@sobychacko once the log output stops, what's the output of `docker-compose ps`?

**Comment by sobychacko** [comment]
@rmoff the connect's status says `unhealthy` at that point.

**Comment by rmoff** [comment]
what's the full output?

**Comment by sobychacko** [comment]
```
 docker-compose ps
     Name                    Command                   State                      Ports
-----------------------------------------------------------------------------------------------------
elasticsearch     /usr/local/bin/docker-entr ...   Exit 137
kafka             /etc/confluent/docker/run        Up               0.0.0.0:9092->9092/tcp
kafka-connect     bash -c echo "Installing C ...   Up (unhealthy)   0.0.0.0:8083->8083/tcp, 9092/tcp
kafkacat          /bin/sh -c apk add jq;           Up
                  wh ...
kibana            /usr/local/bin/dumb-init - ...   Up               0.0.0.0:5601->5601/tcp
ksqldb            /usr/bin/docker/run              Up               0.0.0.0:8088->8088/tcp
mysql             docker-entrypoint.sh mysqld      Up               0.0.0.0:3306->3306/tcp, 33060/tcp
neo4j             /sbin/tini -g -- /docker-e ...   Exit 137
schema-registry   /etc/confluent/docker/run        Up               0.0.0.0:8081->8081/tcp
zookeeper         /etc/confluent/docker/run        Up               2181/tcp, 2888/tcp, 3888/tcp
```

**Comment by rmoff** [comment]
Have you allocated sufficient memory (>8GB) ?

**Comment by sobychacko** [comment]
Oh, That could be it. No, I just went with the default settings as I was trying your tutorial real quick. I will try that later. Thank you!

**Comment by sobychacko** [comment]
@rmoff All good now after I bumped up the memory settings to 8 GB. Sorry for the false alarm. Thanks for the help!

**Comment by rmoff** [comment]
👍

**Comment by LeamonLee** [comment]
> Have you allocated sufficient memory to Docker (>8GB) ?

@rmoff Hi, I'm having the same issue now. Do I need to set up anything in my docker-compose file to allocate 8GB memory for my kafka-connect container? Or just making sure that the server I'm running has more than 8GB would be fine?

**Comment by rmoff** [comment]
you need to configure Docker itself (at least on Mac and Windows) to have
8GB assigned to it. It's an option in the desktop app settings for Docker


-- 

Robin Moffatt | Senior Developer Advocate | robin@confluent.io | @rmoff

**Comment by LeamonLee** [comment]
@rmoff Thanks sir. Now I've moved to Linux, but still getting the same error. Here's the log of kafka-connect:

kafka-connect       | [2021-03-03 07:10:11,850] WARN The configuration 'log4j.loggers' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'config.storage.topic' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'metrics.context.connect.group.id' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'rest.advertised.host.name' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'group.id' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'status.storage.topic' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'plugin.path' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'internal.key.converter.schemas.enable' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'rest.port' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'config.storage.replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'internal.key.converter' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'metrics.context.connect.kafka.cluster.id' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,851] WARN The configuration 'log4j.appender.stdout.layout.conversionpattern' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,852] WARN The configuration 'status.storage.replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,852] WARN The configuration 'internal.value.converter.schemas.enable' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,852] WARN The configuration 'internal.value.converter' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,852] WARN The configuration 'offset.storage.replication.factor' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,852] WARN The configuration 'offset.storage.topic' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,852] WARN The configuration 'log4j.root.loglevel' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,852] WARN The configuration 'value.converter' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,852] WARN The configuration 'key.converter' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig:369)
kafka-connect       | [2021-03-03 07:10:11,852] INFO Kafka version: 6.1.0-ccs (org.apache.kafka.common.utils.AppInfoParser:119)
kafka-connect       | [2021-03-03 07:10:11,852] INFO Kafka commitId: 5496d92defc9bbe4 (org.apache.kafka.common.utils.AppInfoParser:120)
kafka-connect       | [2021-03-03 07:10:11,852] INFO Kafka startTimeMs: 1614755411852 (org.apache.kafka.common.utils.AppInfoParser:121)
kafka-connect       | [2021-03-03 07:10:11,898] INFO App info kafka.admin.client for adminclient-8 unregistered (org.apache.kafka.common.utils.AppInfoParser:83)
kafka-connect       | [2021-03-03 07:10:11,900] INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics:668)
kafka-connect       | [2021-03-03 07:10:11,900] INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics:672)
kafka-connect       | [2021-03-03 07:10:11,900] INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics:678)
kafka-connect       | [2021-03-03 07:10:11,901] ERROR [Worker clientId=connect-1, groupId=compose-connect-group] Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:303)
kafka-connect       | org.apache.kafka.common.config.ConfigException: Topic 'docker-connect-offsets' supplied via the 'offset.storage.topic' property is required to have 'cleanup.policy=compact' to guarantee consistency and durability of source connector offsets, but found the topic currently has 'cleanup.policy=delete'. Continuing would likely result in eventually losing source connector offsets and problems restarting this Connect cluster in the future. Change the 'offset.storage.topic' property in the Connect worker configurations to use a topic with 'cleanup.policy=compact'.
kafka-connect       |   at org.apache.kafka.connect.util.TopicAdmin.verifyTopicCleanupPolicyOnlyCompact(TopicAdmin.java:420)
kafka-connect       |   at org.apache.kafka.connect.storage.KafkaOffsetBackingStore$1.run(KafkaOffsetBackingStore.java:116)
kafka-connect       |   at org.apache.kafka.connect.util.KafkaBasedLog.start(KafkaBasedLog.java:130)
kafka-connect       |   at org.apache.kafka.connect.storage.KafkaOffsetBackingStore.start(KafkaOffsetBackingStore.java:128)
kafka-connect       |   at org.apache.kafka.connect.runtime.Worker.start(Worker.java:197)
kafka-connect       |   at org.apache.kafka.connect.runtime.AbstractHerder.startServices(AbstractHerder.java:128)
kafka-connect       |   at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:289)
kafka-connect       |   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
kafka-connect       |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
kafka-connect       |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
kafka-connect       |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
kafka-connect       |   at java.base/java.lang.Thread.run(Thread.java:834)
kafka-connect       | [2021-03-03 07:10:11,907] INFO Stopped http_8083@ffa60c9{HTTP/1.1, (http/1.1)}{0.0.0.0:8083} (org.eclipse.jetty.server.AbstractConnector:381)
kafka-connect       | [2021-03-03 07:10:11,947] INFO DefaultSessionIdManager workerName=node0 (org.eclipse.jetty.server.session:334)
kafka-connect       | [2021-03-03 07:10:11,948] INFO No SessionScavenger set, using defaults (org.eclipse.jetty.server.session:339)
kafka-connect       | [2021-03-03 07:10:11,949] INFO node0 Scavenging every 660000ms (org.eclipse.jetty.server.session:132)
kafka-connect       | [2021-03-03 07:10:12,357] INFO Started o.e.j.s.ServletContextHandler@7bbab132{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler:916)
kafka-connect       | [2021-03-03 07:10:12,357] INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect:57)
kafka-connect       | [2021-03-03 07:10:12,357] INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect:67)
kafka-connect       | [2021-03-03 07:10:12,357] INFO [Worker clientId=connect-1, groupId=compose-connect-group] Herder stopping (org.apache.kafka.connect.runtime.distributed.DistributedHerder:682)
kafka-connect       | [2021-03-03 07:10:17,358] INFO [Worker clientId=connect-1, groupId=compose-connect-group] Herder stopped (org.apache.kafka.connect.runtime.distributed.DistributedHerder:702)
kafka-connect       | [2021-03-03 07:10:17,358] INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect:72)

And here's my docker-compose setting:
kafka-connect:
      # image: kafka-connect-base   Error
      image: confluentinc/cp-kafka-connect-base
      container_name: kafka-connect
      restart: always
      depends_on:
        - zookeeper1
        - zookeeper2
        - kafka1
        - kafka2
        
      ports:
        - 8083:8083
      environment:
        CONNECT_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9095"
        CONNECT_REST_PORT: 8083
        CONNECT_GROUP_ID: compose-connect-group
        CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
        CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
        CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
        # CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter       # This field is required
        CONNECT_KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
        # value.converter.schemas.enable: true
        # CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter              # This field is required
        # CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'    # This field is required
        CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
        CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
        CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
        CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
        CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
        CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
        CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
        CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/'
      command: 
      - bash 
      - -c 
      - |
        # Install connector plugins
        # This will by default install into /usr/share/confluent-hub-components/ so make
        #  sure that this path is added to the plugin.path in the environment variables 
        confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:11.0.0
        # Launch the Kafka Connect worker
        /etc/confluent/docker/run &
        # Don't exit
        sleep infinity
      volumes:
        - $PWD/data:/data

Could you give me some suggestions? Thanks

**Comment by rmoff** [comment]
@LeamonLee since this is a custom Docker Compose and not one from `demo-scene` I think it would be best to take this over to the Confluent Community Forum and we can discuss it there: https://forum.confluent.io/

**Comment by LeamonLee** [comment]
@rmoff Sure thing! I just took this over there. Thanks for your support!

**Comment by harshagarwal00** [comment]
This still helped me today .. if a warning could be mentioned in Readme file to the repo would be gr8 :)

**Comment by sonamawachar0110** [comment]
Thank you @rmoff . Your suggestion helped me too.
