### ISSUE TITLE
MS SQL Server driver is not registering in Kafka Connect Runtime Log

### ISSUE THREAD

**Issue by tprasad01** [confluentinc/demo-scene#124]
I  am trying to connect to MS SQL Server with io.confluent.connect.jdbc.JdbcSourceConnector, so i put mssql-jdbc-7.4.1.jre8.jar in following path in kafka connect runtime.
 /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib

and CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/'

The problem is MS SQL server driver is not loading & registering in Kafka connect runtime.
But some other plugin drivers like oracle, mysql are registering which are there in same folder above.

Kafka connect runtime log is below.

kafka-connect      | [2020-05-08 13:00:32,528] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSourceConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect      | [2020-05-08 13:00:32,528] INFO Added plugin 'io.confluent.connect.jdbc.JdbcSinkConnector' (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect      | [2020-05-08 13:00:32,530] DEBUG Registered java.sql.Driver: jTDS 1.3.1 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect      | [2020-05-08 13:00:32,558] DEBUG Registered java.sql.Driver: oracle.jdbc.OracleDriver@1fde4f40 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect      | [2020-05-08 13:00:32,563] DEBUG Registered java.sql.Driver: org.postgresql.Driver@290aeb20 to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
kafka-connect      | [2020-05-08 13:00:32,566] DEBUG Registered java.sql.Driver: org.sqlite.JDBC@4393593c to java.sql.DriverManager (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)

 What should i do to load and register MS SQL Server driver in Kafka Connect Runtime?

**Comment by tprasad01** [comment]
mssql-jdbc-7.4.1.jre8.jar in following path in kafka connect and available at runtime is not loading and registering as MS SQL server driver.
/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib

CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/'

My requirement is to connect to the MS SQL server with JDBC source connector.
Could someone suggest me what would be right approach ?

**Comment by tprasad01** [comment]
$find / -name kafka-connect-jdbc*.jar
/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/kafka-connect-jdbc-5.4.1.jar

I have put MS SQL driver in same directory along with kafka-connect-jdbc-5.4.1.jar

**Comment by rmoff** [comment]
@tprasad01 did you get it working? What was the problem?
