### ISSUE TITLE
How to set up cloudkarafka brokers for the confluent rabbitmq source connector?

### ISSUE THREAD

**Issue by spicoflorin** [confluentinc/demo-scene#125]
Hello!

I would like to set up the rabbit source connector that is using kafka brokers provided by cloud kafka. 
I have detailed described  in this post 

https://stackoverflow.com/questions/61913141/how-to-set-up-cloudkarafka-brokers-for-the-confluent-rabbitmq-source-connector

the issue that I'm facing of.

Can you please advice?
Thank you.
Regards,
 Florin

**Comment by rmoff** [comment]
I can provide a solution to running it on Confluent Cloud if that helps? ;-)

**Comment by spicoflorin** [comment]
Hello!

 While it can be helpful, it is Confluent Cloud specific configuration. 
What I would like to clarify are the following configuration for the connector:
1.  Is it mandatory to provide these configurations ?

  ```
"bootstrap.servers":"cloudkafkabroker:9094",
    "sasl.jaas.config": "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"username\" password=\"password\";",
    "security.protocol":"SASL_SSL",
   "sasl.mechanism":"SCRAM-SHA-256",   
```
2. Why the connector that is running inside container doesn't use the underlying kafka brokers provided in the docker-compose via the environment variables:
```
CONNECT_BOOTSTRAP_SERVERS: "my-cloudkafka-brokers:9094"
      CONNECT_SECURITY_PROTOCOL: "SASL_SSL"
      CONNECT_SASL_MECHANISM: "SCRAM-SHA-256"
      CONNECT_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="username" password="hidden";'
```

3. For me it is not clear what key pairs should be used for connector configurations, regarding the 

 ```
"bootstrap.servers"
"sasl.jaas.config"
 "security.protocol"
  "sasl.mechanism"   
```
In my opinion they should be the same disregarding the kafka broker providers. I have seen for  same connector, configuration like these key pairs:
```
"confluent.topic.bootstrap.servers",
    "confluent.topic.sasl.jaas.config"
        "confluent.topic.security.protocol"
        "confluent.topic.sasl.mechanism"

```

or like these:
 ```
"producer.bootstrap.servers",
    "producer.sasl.jaas.config"
        "producer.security.protocol"
        "producer.sasl.mechanism"
```
When you should use one over the others? What is about producer prefix?

4.  In the configuration for the connector it is mandatory to use the 
 "confluent.license":""? When and why you should add this config?

I look forward for your answers.
Thanks.

**Comment by rmoff** [comment]
It's best if you speak to your cloud provider for help connecting to their brokers. 

For general information about how to configure Kafka Connect and answer your questions above see https://docs.confluent.io/current/connect/index.html
