### ISSUE TITLE
request.timeout.ms override

### ISSUE THREAD

**Issue by ijuma** [confluentinc/demo-scene#126]
I see a few examples where we do things like:

```
request.timeout.ms=20000
```

This seems unnecessary since the default is reasonable (30s). It would be nice to remove it to keep things simpler.

**Comment by ijuma** [comment]
Thoughts @rmoff?

**Comment by rmoff** [comment]
At one point these were the incantations needed for things to work with Cloud. 
Happy to remove them if that's no longer the case :-)

/cc @riferrei
