### ISSUE TITLE
Set RabbitMQConnector kafka key based on a message field value  

### ISSUE THREAD

**Issue by spicoflorin** [confluentinc/demo-scene#127]
Hello!
I have read the great article 

https://rmoff.net/2020/01/08/streaming-messages-from-rabbitmq-into-kafka-with-kafka-connect/.

I would like to know how/if it possible to configure the rabbitmq source connector:
 1.  to take a field from the payload message as a value for the key for the kafka message
2. to specify a static value value for the key for the kafka message     

Example for the mentioned article:
1. specify  "transaction" field value (e.g. PAYMENT) to be key value for the kafka message
RabbitMQMessage
```
{
  "transaction": "PAYMENT",
  "amount": "$125.0",
  "timestamp": "Wed 8 Jan 2020 10:41:45 GMT"
}
```
Kafka message, the value of the field transaction to be set as value for the kafka key message : 
```
"key": "PAYMENT"
"value": byte value for the RABBITMQMessage
```
2. Specify my own key value, meaning that the key value for the Kafka Message o be configured static as "PAYMENT"
Kafka message: 
```
"key": "PAYMENT"
"value": byte value for the RABBITMQMessage
```

 I would prefer a solution for the first example, in order to have a dynamic configuration,

**Comment by rmoff** [comment]
You should be able to use a Single Message Transform to do this: https://docs.confluent.io/current/connect/transforms/valuetokey.html#valuetokey
