### ISSUE TITLE
[Question] Docker-compose and relatively long time before valid Connector?

### ISSUE THREAD

**Issue by scheung38** [confluentinc/demo-scene#141]
docker-compose -f dc.kafka.yml up (depends_on not shown)

zookeeper:
    image: confluentinc/cp-zookeeper:5.5.0

kafka:
    image: confluentinc/cp-server:5.5.0

rest-proxy:
    image: confluentinc/cp-kafka-rest:5.5.0

schema-registry:
    image: confluentinc/cp-schema-registry:5.5.0

kafka-connect-01:
    image: confluentinc/cp-kafka-connect:5.5.0

ksqldb-server:
    image: confluentinc/cp-ksqldb-server:5.5.0

But 

$ curl -s localhost:8083/connector-plugins|jq '.[].class'|egrep 'SpoolDir'

is not returned until after 3-4 minutes later? Is this normal operation? :

"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirLineDelimitedSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSchemaLessJsonSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.elf.SpoolDirELFSourceConnector"

if this is to be expected then we need to async wait for 3 mins?

<img width="524" alt="Screenshot 2020-08-10 at 21 28 51" src="https://user-images.githubusercontent.com/1273014/89828108-7f6df280-db50-11ea-83a0-f0b6ff34b579.png">

<img width="1023" alt="Screenshot 2020-08-10 at 21 42 26" src="https://user-images.githubusercontent.com/1273014/89829384-66664100-db52-11ea-9d99-70f710e4122e.png">

**Comment by rmoff** [comment]
@scheung38 thanks for raising these issues. It would be great if you can include the solution that you found when you close them :)

**Comment by scheung38** [comment]
There was no issue, just that after docker-compose up, was expecting to 

curl -s localhost:8083/connector-plugins|jq '.[].class'|egrep 'SpoolDir'

empty

then realized it needs to wait 30 secs before 

curl -s localhost:8083/connector-plugins|jq '.[].class'|egrep 'SpoolDir'

"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirJsonSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirLineDelimitedSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.SpoolDirSchemaLessJsonSourceConnector"
"com.github.jcustenborder.kafka.connect.spooldir.elf.SpoolDirELFSourceConnector"
