### ISSUE TITLE
[Question]  "schema.generation.enabled": "true" <-- not capturing the order_id as expected?

### ISSUE THREAD

**Issue by scheung38** [confluentinc/demo-scene#143]
Added 

"schema.generation.key.fields": "order_id", 

in curl:

{
	"connector.class": "com.github.jcustenborder.kafka.connect.spooldir.SpoolDirCsvSourceConnector",
	"topic": "orders_spooldir_01",
	"input.path": "/data/unprocessed",
	"finished.path": "/data/processed",
	"error.path": "/data/error",
	"input.file.pattern": ".*\\.csv",
	"schema.generation.enabled": "true",
	"schema.generation.key.fields": "order_id",
	"csv.first.row.as.header": "true"
}

but the generated:

➜  data git:(master) ✗ docker exec kafkacat kafkacat -b kafka:29092 -t orders_spooldir_01 -C -o-1 -J -s key=s -s value=avro -r http://schema-registry:8081 | jq '.'
{
  "topic": "orders_spooldir_01",
  "partition": 0,
  "offset": 999,
  "tstype": "create",
  "ts": 1597701710423,
  "headers": [
    "file.name",
    "orders.csv",
    "file.path",
    "/data/unprocessed/orders.csv",
    "file.length",
    "83034",
    "file.offset",
    "1001",
    "file.last.modified",
    "2020-08-17T20:40:20.000Z"
  ],
  "key": "Struct{}", <---- Empty?

is still Empty?

expecting:

 "key": "Struct{order_id=1000}",

EDIT:

Worked but needed to restart Kafka cluster?

**Comment by rmoff** [comment]
Hi @scheung38, the best place to ask general questions about the connectors is one of these resources: 

→ Mailing list: https://groups.google.com/forum/#!forum/confluent-platform
→ Slack group: http://cnfl.io/slack

The issues on this repo is more for tracking actual bugs with the published demos. Thanks, and good luck on your Kafka journey :)
