### ISSUE TITLE
[Question] How to modify these examples, say csv to kafka to work with Azure?

### ISSUE THREAD

**Issue by scheung38** [confluentinc/demo-scene#147]
for example if needing to place CSV input.path but in this case it is located in subscription file share

top level:
  unprocessed
  processed
  error

how to modify the yml files to point to Azure?

**Comment by rmoff** [comment]
@scheung38 it's great you're getting value from these examples, but please use http://cnfl.io/slack or https://groups.google.com/forum/#!forum/confluent-platform for questions - you can always link to the code in question for context. Thanks.
