### ISSUE TITLE
reference setup.sh

### ISSUE THREAD

**Issue by Negrero** [confluentinc/demo-scene#161]
In the oracle-ksql-elasticsearch example, the  file that is inside docker-compose/scripts should/setup.sh be in the docker-compose/setup.sh directory because the references inside are made to that directory in addition to the context of docker-compose:
docker-compose exec connect-debezium bash -c '**/scripts/**create-ora-source-debezium-xstream.sh'

can I do a pull request?

**Comment by rmoff** [comment]
Hi, a PR would be great, thank you!
