### ISSUE TITLE
Tiered-Storage readme.md consume command error

### ISSUE THREAD

**Issue by jssnipes** [confluentinc/demo-scene#170]
(Reference to tiered-storage/readme.md file) Looks like the command given for the consumer has a different topic and port than expected ... it should be the below.  Let me know if you would like for me to submit a pull request for this.  

kafka-consumer-perf-test --topic test-topic \
    --messages 5000 \
    --threads 1 \
    --broker-list localhost:9091 \
    --timeout 60000 \
    --consumer.config config/consumer.config

**Comment by Marcinthecloud** [comment]
Thanks - yes the ports should be 9091 per the docker compose file. I should be able to get to this later this week or if you'd like, you can submit a PR.
