### ISSUE TITLE
Having problem with specific.protobuf.value.type in yaml config using Spring Cloud Kafka binder

### ISSUE THREAD

**Issue by mperrault** [confluentinc/demo-scene#189]
When using the Spring Cloud Kafka binder, I am having a problem applying the 'specific.protobuf.value.type' config setting when using KafkaProtobufSerde. In my StreamProcessor class, I want to be able to deserialize my protobuf classes using the the 'specific' classes specified in config (protobuf generated).
Please see sample code: https://github.com/mperrault/specific-protobuf-issue
In my EventStreamProcessor.consume method, the eventType1Stream should be deserialized as EventType1 instances, and the eventType2Stream should be EventType2 instances if this config setting is applied properly to these channels. 
The consume method invocation will fail with ClassCastExceptions indicating that the events types are of type DynamicMessage (which is what you would expect if KafkaProtobufSerde had no 'specific' config applied). 
I experimented with moving the specific.protobuf.value.type setting to different locations in the yaml file, but had no success in getting this recognized at the channel level. Note that 'specific' config does work at the spring.kafka.properties.specific.protobuf.value.type location, but this ends up causing ALL channels that have been configured for KafkaProtobufSerde to use this 'specific' value type - I want to be able to set 'specific'  per channel.

**Comment by mperrault** [comment]
Thanks!

**Comment by gAmUssA** [comment]
hi @mperrault 

It looks like you have some complex code there. Some of the components managed by SCS. some of them plain spring-kafka.
Could you simplify your problem in 2-3 sentenses so I can write SCS app from the scratch to reproduce problem with protobuf serializer.
Thank you

**Comment by mperrault** [comment]
- Refer to Confluent Documentation:
https://www.confluent.io/blog/spring-for-apache-kafka-deep-dive-part-2-apache-kafka-spring-cloud-stream/
and section "Overview of Kafka Streams support in Spring Cloud Stream".

- I want to use a protobuf generated class (e.g. PBuffClass1) for the value of input1, and another protobuf generated class for value of input2 (e.g. PBuffClass2). So, the signature of 'process' would look like:
public KStream<String, Long> process(@Input("input1") KStream<String, PBuffClass1> userClicksStream,
                                 @Input("input2") KTable<String, PBuffClass2> userRegionsTable)

- what does this look like in the application.yml file for the Serdes config for input1 and input2 using "specific.protobuf.value.type" ?

**Comment by rmoff** [comment]
If this is still an open issue, please post details to https://forum.confluent.io/. Thanks.
