### ISSUE TITLE
kafka connect jar links don't work

### ISSUE THREAD

**Issue by sparrowV** [confluentinc/demo-scene#198]
Greetings,
Kafka connect does not download jars with `curl https://cdn.mysql.com/Downloads/Connector-J/mysql-connector-java-8.0.16.tar.gz` as specified in the `command` section of docker-compose file.

![kafka-prob](https://user-images.githubusercontent.com/29176362/110811175-e5198d00-829f-11eb-8b98-123476539978.PNG)
I also logged in to the container did it manually and it did not download the jar.(see above pic)

I also cant find download jars in the `/usr/share/java` that I configured in Kafka connect.
![pwd](https://user-images.githubusercontent.com/29176362/110812250-e4352b00-82a0-11eb-9970-0d492047b49b.PNG)

Attaching docker-compose file, that's almost the same as yours.

[docker-compose.zip](https://github.com/confluentinc/demo-scene/files/6124092/docker-compose.zip)

**Comment by rmoff** [comment]
Thanks for reporting. The versions do change, I hit this myself today too. 
The latest is `https://cdn.mysql.com/Downloads/Connector-J/mysql-connector-java-8.0.23.tar.gz`. I'll try and fix this across the repo.

**Comment by rmoff** [comment]
Fixed https://github.com/confluentinc/demo-scene/commit/c216326ad0b8cd74cf5327e85e66faab85017e66
