### ISSUE TITLE
[Question] How do you configure the MQTT client id in a MqttConnector?

### ISSUE THREAD

**Issue by erikhh** [confluentinc/demo-scene#204]
I'm evaluating `io.confluent.connect.mqtt.MqttSourceConnector` and `io.confluent.connect.mqtt.MqttSinkConnector`.

I notice that the connector misses MQTT messages from Mosqiutto when connect is not running. Even tough `mqtt.clean.session.enabled` is set to `false`. 
In the Mosquitto logs I see that the connector uses a different MQTT client id after each restart. If I could fix the client id, the MQTT borker would deliver message received when the connector reconnects. However, in the [documentation](https://docs.confluent.io/kafka-connect-mqtt/current/mqtt-source-connector/mqtt_source_connector_config.html)  I can't find any property to set the MQTT client id. 

I'm wondering, is this bit of configuration undocumented or just missing altogether?

**Comment by rmoff** [comment]
Hi @erikhh, the best place for this kind of question is one of the community platforms: https://confluent.io/community/ask-the-community/
