### ISSUE TITLE
Cannot able to connect to ksql 

### ISSUE THREAD

**Issue by cibi246** [confluentinc/demo-scene#213]
Connecting to ksql keeps waiting for more than 30 minutes

![image](https://user-images.githubusercontent.com/5158953/121669556-0cb00980-caca-11eb-8f68-0e442a3e5bb4.png)

**Comment by rmoff** [comment]
Hi,

Please can you post details of this (including which Docker Compose you're running, machine memory allocated, output of docker ps -a etc) to the Kafka Connect category on https://forum.confluent.io/ and someone will hopefully help out there. thanks.
