### ISSUE TITLE
smoke_sensor_simulator error

### ISSUE THREAD

**Issue by aristidebordoli** [confluentinc/demo-scene#217]
Good afternoon
I am trying to produce smoke data using the producer configuration with avro.
Below the screenshot of the error I got:
![image](https://user-images.githubusercontent.com/44033911/124358624-6f0bae00-dc21-11eb-958a-d9d93902b736.png)

Thanks and Regards,
Aristide

**Comment by rmoff** [comment]
Is this from a demo in this repository? If so which one?
