### ISSUE TITLE
Updating community-components-only repo

### ISSUE THREAD

**Issue by marcelfenerich** [confluentinc/demo-scene#230]
It would be great, if the community-components-only repo get updated.

The community components are a great start for beginners, so I think it would be nice to get it a bit more updated.

Also the docker images used in this yml file are set as deprecated on docker hub.

The enviroments variables set on yml file are extremelly important, but unfortunatelly I'm not sure if they remain the same on newer versions of confluent platform.

Thanks.

**Comment by marcelfenerich** [comment]
I just checked there's a updated version on official docs.

https://raw.githubusercontent.com/confluentinc/cp-all-in-one/6.2.0-post/cp-all-in-one-community/docker-compose.yml

**Comment by rmoff** [comment]
`demo-scene`, by design, is not kept up to date. Content is updated on an ad-hoc basis, usually when someone comes to use something which they then update and test. So, PRs are open and I'd be happy if you'd like to submit one for updating the Docker Compose you mention :)
