### ISSUE TITLE
How to convert a Avro record

### ISSUE THREAD

**Issue by abstract-thinking** [confluentinc/demo-scene#236]
Hi, 

I have question about this [sample code](https://github.com/confluentinc/demo-scene/blob/master/spring-kafka-ccloud-course/spring-ccloud-avro/src/main/java/io/confluent/developer/springccloudavro/SpringCcloudAvroApplication.java)

The consumer and the deseralisation works fine. As the next step I want use a new class copy the values and send it back to Kafka with a new topic.

Do you have a recommendation how to do? Or where in the documenation I could find an example.
I think it's called processor and I did not get it to run correct with StreamBuilder.

I forgot to mention that a SchemaRegistry is used.

Thanks,
Markus

**Comment by rmoff** [comment]
Hi Markus, 
Sorry for the delay responding. If this is still an issue, please post this over at https://forum.confluent.io/ and I'll try to get someone to help you there.
