### ISSUE TITLE
Flatten nested JSON data fields and whitelist them and Flatten SMT fails on arrays

### ISSUE THREAD

**Issue by vishaldhanani** [confluentinc/demo-scene#240]
Hello,

I am getting the below error while trying to flatten nested JSON data in my elastic sink connector. my main purpose is to whitelist the required fields for my elastic index. When I tried to use a direct whitelist that will not consider nested fields in it. so that's the reason to do flatten first and then rename those nested fields and then whitelist those required fields.  Is there any other way we can achieve this? 

`Caused by: org.apache.kafka.connect.errors.DataException: Flatten transformation does not support class java.util.ArrayList for record without schemas`

Thank you for your help in advance!

**Comment by rmoff** [comment]
Hi @vishaldhanani , please can you post this over at https://forum.confluent.io/
thanks.

**Comment by vishaldhanani** [comment]
Hi @rmoff, I have already posted in the [Confluent connect slack](https://confluentcommunity.slack.com/archives/C49L0V3L7/p1645483982655259) channel but didn't get any response. 

Thank you!
