### ISSUE TITLE
Not real issue, but a question

### ISSUE THREAD

**Issue by weiseldk** [confluentinc/demo-scene#247]
Hi,

I was following the code examples, can you help out executing curl commands for kafka connect from windows machine using docker, seem to be not working. 

Thank you sir.

**Comment by weiseldk** [comment]
@rmoff  - Kafka-connect-zero-to-hero, I am new with kafka, but trying hard to execute, its not plug and play for sure when you try through a win desktop.  :)

**Comment by rmoff** [comment]
The best way to get started on Windows is either with Docker or via WSL: https://www.confluent.io/blog/set-up-and-run-kafka-on-windows-linux-wsl-2/ / https://www.confluent.io/blog/set-up-and-run-kafka-on-windows-and-wsl-2/
