### ISSUE TITLE
Partitioning with keys (Grouping by the key) in S3 sink kafka connect

### ISSUE THREAD

**Issue by arezvani** [confluentinc/demo-scene#251]
Hi,
Can we partition our output in s3 sink connector with key?

For example if I have these couple of key and value in kafka topic:

key : value
1 : 1
2 : 2
3 : 3
1 : 4 
2 : 5
3 : 6

our output should be like that:

1.json -> 1,4
2.json -> 2,5
3.json -> 3,6

**Comment by rmoff** [comment]
Please ask general questions over at https://www.confluent.io/en-gb/community/ask-the-community/. Thanks.
