### ISSUE TITLE
ATM Data Generator not emitting right transactions

### ISSUE THREAD

**Issue by MuhammadAdeelUsman** [confluentinc/demo-scene#35]
Hi Robin, 

I'm following your demo. I got issue with Gess. As you are using UK ATM transaction data. I have downloaded new Zealand ATM data from open street map. As per instruction I have generate csv file and then I copied atmnz_export.csv under data directory and update gess.conf file accordingly. 

Restart the container and verity gess is emitting NZ ATM transaction data by this command  

    nc -v -u -l 6900 

but when I tried push same transaction in new topic using following command 

    nc -v -u -l 6900 | \
    docker run --interactive --rm --network ksqlatmfrauddetection_default confluentinc/cp-kafkacat \
    kafkacat -b kafka:29092 -P -t atm_txns_akl

I got UK ATM transaction in topic. If I stop and rerun the same command it start pushing NZ data. it is not consistent. 

I don't know how its picking UK ATM transaction data even I have deleted all files from gess data directory but it still emitting UK ATM data.  Any thoughts ?

**Comment by rmoff** [comment]
How are you running gess? From the docker image referenced in the docker-compose? or standalone?

**Comment by MuhammadAdeelUsman** [comment]
Thanks for reply. I'm using docker-compose to setup everything. I have copied my csv file in docker container and update conf file as well and restart the container. Tot verify the change if I run the nc-v -I 6900 I can see NZ ATM transaction but if stop and rerun the same command its start showing UK ATM transaction. Even if I run second command mentioned above to push message in new topic sometime it show NZ and sometime UK one. I'm facing another issue, if I use UK file to generate ATM transaction and push new message in same topic ATM_TXNS_GESS I can see new transaction data in KSQL but its not being replicated in Elasticsearch. I have check the status of JDBC connector which is  up and running but somehow it's not working. Sorry for dump questions I have recently start playing with ELK and kafka.

**Comment by rmoff** [comment]
I'd probably look at building my own version of the `gess` image, there's the source repo and Dockerfile here: https://github.com/rmoff/gess/blob/master/Dockerfile
