### ISSUE TITLE
Cube: overview diagram should show mobile devices accessing the REST/VPC environment

### ISSUE THREAD

**Issue by miguno** [confluentinc/demo-scene#40]
https://github.com/confluentinc/demo-scene/tree/master/ccloud-cube-demo

The image at https://github.com/confluentinc/demo-scene/raw/master/ccloud-cube-demo/images/rest-api-call.png should show how the mobile devices (= what the users do) interact with the REST proxy.  I read the intro paragraphs and kept wondering where, in the diagram, the users are represented.

Also, the intro paragraph talks about "the application" and "the moves", but lacks even a 1-liner description of what "the Cube" (the app, the moves) actually is:

> This code contains a sample application called "The Cube" that allow users to interact with Kafka clusters running on Confluent Cloud by using their mobile devices. While users play with the application from their mobile devices, events containing their moves are emitted to a topic.

I found this info much later:
> The application presents the user with a cube that moves as the user moves its hands and body. It relies on the device orientation API found in most modern devices.

And typo here:
> Anyone capable of perfectly positioning the cube using the coordinates **the** represents the number three will be shown in the output of a KSQL query.

**Comment by riferrei** [comment]
Hi @miguno, thanks for pointing out these items. I've fixed some and gonna work in a better representative diagram.

**Comment by rmoff** [comment]
Closing as pretty sure this is stale/legacy issue now.
