### ISSUE TITLE
Streaming Movie ratings: Docker and Kubernetes support

### ISSUE THREAD

**Issue by gAmUssA** [confluentinc/demo-scene#62]
Add support of

* [x] add uberjar packaging 
* [x] Docker packaging (separate project with docker / jib configuration)
* [x] Kubernetes deployment with `Deployment` and `StatefulSet`
* [ ] Add helm chart for Kubernetes deployment

cc @tlberglund

**Comment by rmoff** [comment]
@gAmUssA can this be closed?
