### ISSUE TITLE
ksql query timeout error in python

### ISSUE THREAD

**Issue by allenansari174** [confluentinc/demo-scene#73]
I have an issue running ksql query from python. always I got timeout error:

timeout Traceback (most recent call last)
/usr/lib/python3/dist-packages/urllib3/response.py in _error_catcher(self)
301 try:
--> 302 yield
303

/usr/lib/python3/dist-packages/urllib3/response.py in read_chunked(self, amt, decode_content)
600 break
--> 601 chunk = self._handle_chunk(amt)
602 decoded = self._decode(chunk, decode_content=decode_content,

/usr/lib/python3/dist-packages/urllib3/response.py in _handle_chunk(self, amt)
566 returned_chunk = self._fp._safe_read(self.chunk_left)
--> 567 self._fp._safe_read(2) # Toss the CRLF at the end of the chunk.
568 self.chunk_left = None

/usr/lib/python3.6/http/client.py in _safe_read(self, amt)
611 while amt > 0:
--> 612 chunk = self.fp.read(min(amt, MAXAMOUNT))
613 if not chunk:

/usr/lib/python3.6/socket.py in readinto(self, b)
585 try:
--> 586 return self._sock.recv_into(b)
587 except timeout:

timeout: timed out

During handling of the above exception, another exception occurred:

ReadTimeoutError Traceback (most recent call last)
/usr/lib/python3/dist-packages/requests/models.py in generate()
744 try:
--> 745 for chunk in self.raw.stream(chunk_size, decode_content=True):
746 yield chunk

/usr/lib/python3/dist-packages/urllib3/response.py in stream(self, amt, decode_content)
431 if self.chunked and self.supports_chunked_reads():
--> 432 for line in self.read_chunked(amt, decode_content=decode_content):
433 yield line

/usr/lib/python3/dist-packages/urllib3/response.py in read_chunked(self, amt, decode_content)
625 if self._original_response:
--> 626 self._original_response.close()

/usr/lib/python3.6/contextlib.py in exit(self, type, value, traceback)
98 try:
---> 99 self.gen.throw(type, value, traceback)
100 except StopIteration as exc:

/usr/lib/python3/dist-packages/urllib3/response.py in _error_catcher(self)
306 # there is yet no clean way to get at it from this context.
--> 307 raise ReadTimeoutError(self._pool, None, 'Read timed out.')
308

ReadTimeoutError: HTTPConnectionPool(host='localhost', port=8088): Read timed out.

During handling of the above exception, another exception occurred:

ConnectionError Traceback (most recent call last)
in 
1 query = client.query('select * from user_tweet_count')
----> 2 for item in query: print(item)

/usr/local/lib/python3.6/dist-packages/ksql/api.py in query(self, query_string, encoding, chunk_size, stream_properties, idle_timeout)
69 streaming_response = self._request(endpoint='query', sql_string=query_string, stream_properties=stream_properties)
70 start_idle = None
---> 71 for chunk in streaming_response.iter_content(chunk_size=chunk_size):
72 if chunk != b'\n':
73 start_idle = None

/usr/lib/python3/dist-packages/requests/models.py in generate()
750 raise ContentDecodingError(e)
751 except ReadTimeoutError as e:
--> 752 raise ConnectionError(e)
753 else:
754 # Standard file-like object.

ConnectionError: HTTPConnectionPool(host='localhost', port=8088): Read timed out.

**Comment by rmoff** [comment]
Please raise this as a new issue at https://github.com/confluentinc/ksql/issues/
