### ISSUE TITLE
demo-scene/ksql-workshop master ❯ docker-compose pull error

### ISSUE THREAD

**Issue by gAmUssA** [confluentinc/demo-scene#84]
```
Pulling zookeeper        ... done
Pulling kafka            ... done
Pulling schema-registry  ... done
Pulling kafka-connect    ... done
Pulling ksql-server      ... done
Pulling ksql-cli         ... done
Pulling kafkacat         ... done
Pulling datagen-ratings  ... done
Pulling control-center   ... done
Pulling mysql            ... done
Pulling connect-debezium ... done
Pulling elasticsearch    ... done
Pulling kibana           ... done
Pulling websockets       ... error
Pulling nginx            ... done

ERROR: for websockets  b"pull access denied for ksql-workshop-websockets, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
ERROR: pull access denied for ksql-workshop-websockets, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by russau** [comment]
I'm not getting the same.  I just ran the steps on a clean ec2 instance, `docker-compose up -d` builds websockets container build okay.

```
...snip...
Building websockets
Step 1/9 : FROM node:dubnium-stretch
dubnium-stretch: Pulling from library/node
092586df9206: Pull complete
...snip...
Creating elasticsearch   ... done
Creating mysql         ... done
Creating websockets    ... done
Creating zookeeper     ... done
Creating kafka         ... done
Creating nginx           ... done
Creating kafkacat         ... done
Creating ksql-server      ... done
Creating schema-registry ... done
Creating kibana           ... done
Creating connect-debezium ... done
Creating kafka-connect    ... done
Creating datagen-ratings  ... done
Creating ksql-cli         ... done
Creating control-center   ... done
```

Could it be a docker-compose version thing?  I'm on `docker-compose version 1.24.0, build 0aa59064`.  Could it be an authentication thing?  I'm not logged into a docker registry.   Maybe you have expired credentials that are interfering?

I'll experiment with the authentication part, and see if that's a factor.

**Comment by gAmUssA** [comment]
@russau shall we fix prerequisites doc then?

**Comment by russau** [comment]
I'm not sure if it is the docker-compose version causing the issue.  Does a `docker-compose up -d --build` force the container to get built in your environment.  If this fixes it for you I'll update the instructions.

Are you running `docker-compose` from the `demo-scene/ksql-workshop` directory?  Double check you are in the right location and the Dockerfile is present with `cat ./websockets/Dockerfile`.

**Comment by russau** [comment]
I've also attempted this on Ubuntu docker-compose 1.22.0 with no problem.

Can you try `docker-compose up -d --build`?  If that's not happy try a `docker logout` to see if creds are the issue.

**Comment by russau** [comment]
I see the problem - I missed the `docker-compose pull` in the title.  If I remove the `image: ksql-workshop-websockets` from `docker-compose.yml` it won't attempt to pull the image that doesn't exit.

**Comment by russau** [comment]
I've created a PR - apologies for the breakage and confusion, I wasn't aware of the `docker-compose pull` in the prerequisites.
