### ISSUE TITLE
rail-data-streaming-pipeline - Ingest data

### ISSUE THREAD

**Issue by aditya-08** [confluentinc/demo-scene#89]
Trying to set up rail-data-stream locally. getting below error.

**Adityas-MacBook-Pro:cif_schedule adityapadhi$ ./00_ingest_schedule.sh 
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
./00_ingest_schedule.sh: line 4: /../../set_credentials_env.sh: No such file or directory
gunzip: unknown compression format
gunzip: unknown compression format
gunzip: unknown compression format
gunzip: unknown compression format
Adityas-MacBook-Pro:cif_schedule adityapadhi$ 
Adityas-MacBook-Pro:cif_schedule adityapadhi$** 

any advise how to resolve?

some more info..
**Adityas-MacBook-Pro:cif_schedule adityapadhi$ curl -s -L -u "$NROD_USERNAME:$NROD_PASSWORD" "https://datafeeds.networkrail.co.uk/ntrod/CifFileAuthenticate?type=CIF_EA_TOC_FULL_DAILY&day=toc-full"
<html><head><title>Apache Tomcat/7.0.27 - Error report</title><style></style> </head><body><h1>HTTP Status 401 - User not subscribed to CIF_EA_TOC_FULL_DAILY</h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u>User not subscribed to CIF_EA_TOC_FULL_DAILY</u></p><p><b>description</b> <u>This request requires HTTP authentication (User not subscribed to CIF_EA_TOC_FULL_DAILY).</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/7.0.27</h3></body></html>Adityas-MacBook-Pro:cif_schedule adityapadhi$ echo $NROD_USERNAME
padhi@protonmail.com
Adityas-MacBook-Pro:cif_schedule adityapadhi$** 

PS : name of the script is incorrect in set up instructions.

**Comment by aditya-08** [comment]
additional info..below work..

Adityas-MacBook-Pro:cif_schedule adityapadhi$ curl -L -u "$NROD_USERNAME:$NROD_PASSWORD" -o file.gz 'https://datafeeds.networkrail.co.uk/ntrod/CifFileAuthenticate?type=CIF_ALL_FULL_DAILY&day=toc-full'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 93.9M  100 93.9M    0     0  3405k      0  0:00:28  0:00:28 --:--:-- 4333k
Adityas-MacBook-Pro:cif_schedule adityapadhi$ ls -ltr
total 208392
-rwxr-xr-x@ 1 adityapadhi  wheel     15370  3 Oct 06:27 top2500_places.txt
-rwxr-xr-x@ 1 adityapadhi  wheel   5985980  3 Oct 06:27 opencage.json
-rwxr-xr-x@ 1 adityapadhi  wheel       190  3 Oct 06:27 README.md
-rwxr-xr-x@ 1 adityapadhi  wheel      3526  3 Oct 06:27 CifFile_sample.json
-rwxr-xr-x@ 1 adityapadhi  wheel       424  3 Oct 06:27 01_process_schedule.sh
-rwxr-xr-x@ 1 adityapadhi  wheel       136  3 Oct 06:27 00_load_opencage.sh
-rwxr-xr-x@ 1 adityapadhi  wheel      3668  3 Oct 06:27 00_ingest_schedule.sh
**-rw-r--r--  1 adityapadhi  wheel  98536509  6 Oct 09:41 file.gz**
Adityas-MacBook-Pro:cif_schedule adityapadhi$

**Comment by aditya-08** [comment]
resolved.

my bad. wasn't subscribed to correct nationarail feed.

**Comment by rmoff** [comment]
Glad you got it working :)
