### ISSUE TITLE
Trying to use Debezium connector MySQL giving deserialization error

### ISSUE THREAD

**Issue by visakhmurukes** [confluentinc/demo-scene#91]
The kafka topic gets created and starts streaming and task fails with below error soon after

```
{"id":0,"state":"FAILED","worker_id":"kafka-connect:8083","trace":"org.apache.kafka.connect.errors.ConnectException: com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1570956435000, eventType=TABLE_MAP, serverId=1, headerLength=19, dataLength=80, nextPosition=708104, flags=0}...
```

The connector is created as below

```
curl -i -X POST -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/ \
    -d '{
      "name": "debezium-source-source1",
      "config": {
            "connector.class": "io.debezium.connector.mysql.MySqlConnector",
            "database.hostname": "mysql",
            "database.port": "3306",
            "database.user": "username",
            "database.password": "*****",
 	    "database.server.id": "1",
            "database.server.name": "db",
            "table.whitelist": "schema.table",
            "database.history.kafka.bootstrap.servers": "kafka:29092",
            "database.history.kafka.topic": "dbhistory.table" ,
            "include.schema.changes": "true"
       }
    }'
```

The mysql version is 8.0.17
I've created the history topic beforehand as it was giving an error dbtopic is missing at first.

The connector created successfully and started streaming data and soon after task failed with above error. I checked topic and could see initial data it pulled
I've also ensured the MySQL global settings are set as per 
[https://debezium.io/documentation/faq/#what_is_causing_intermittent_code_eventdatadeserializationexception_code_s_with_the_mysql_connector](url)

**Comment by visakhmurukes** [comment]
Found one more thing. Kafka topics using the same connector works fine when connected to local instance of MySQL 5.7.27 version. I checked config variable settings and they're same between both instances. But something is causing kafka connect task to fail with deserialization error for TABLE_MAP event when MySQL version is 8.0.17.

**Comment by rmoff** [comment]
This sounds like something worth raising over at the Debezium project. I'm going to close the ticket here as it's not something to fix at root in `demo-scene`. Thanks.

**Comment by visakhmurukes** [comment]
Sorry
Posted it in Debezium project and got it fixed
You shall close this
