### ISSUE TITLE
KSQL Streams created doesnt create kafka topic on backend

### ISSUE THREAD

**Issue by visakhmurukes** [confluentinc/demo-scene#98]
Tried creating a stream using K-SQL over Kafka topic. The stream got created. But I cant see any corresponding topic created on the background.

**Comment by rmoff** [comment]
Which demo/instructions are you following? What exact commands did you run?

**Comment by visakhmurukes** [comment]
demo_no-more-silos.adoc document and docker-compose within demo-scene/no-more-silos to create the containers

**Comment by rmoff** [comment]
What are the KSQL commands that you ran? 
BTW when you create a KSQL stream on an existing Kafka topic no new topics get created. It's only if you do `CREATE STREAM AS SELECT` / `CREATE TABLE AS SELECT`

**Comment by visakhmurukes** [comment]
Oh Sorry I was not aware of that. I'm a rookie in KSQL/Kafka
Tried creating a stream based on SELECT statement and it created the topic correctly. Thanks for this tip and sorry for the stupidity
One followup question, if I create a table instead of stream using the SELECT, will it also create a topic on Kafka?

**Comment by rmoff** [comment]
No problem :) 

Yes, when you `CREATE TABLE AS SELECT` that also creates a Kafka topic. 

Check out the KSQL docs for more info on the syntax: https://docs.confluent.io/current/ksql/docs/index.html
